version: '3.7'
services:
  postgres:
    image: postgres:14.1
    container_name: postgre-excercise-18b
    restart: always
    #volumes:
    #  - './postgres_data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass1234
    ports:
      - '5432:5432'